# Generated by Django 2.0.1 on 2018-01-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('usercode', models.CharField(default='0000', max_length=20)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
