# Generated by Django 2.0.1 on 2018-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
