# Generated by Django 2.0.1 on 2018-01-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usercode',
            field=models.IntegerField(),
        ),
    ]
