# Generated by Django 2.0.1 on 2018-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180123_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usercode',
            field=models.IntegerField(auto_created=True),
        ),
    ]
