# Generated by Django 2.0.1 on 2018-01-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180123_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usercode',
        ),
    ]
